name: doc-manager

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: doc-manager-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - doc-manager-network

  db:
    image: postgres:15
    container_name: doc-manager-postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doc-manager
    networks:
      - doc-manager-network

networks:
  doc-manager-network:
    driver: bridge