export enum EnvConstants {
    PORT = "PORT",
    NODE_ENV = "NODE_ENV",
    POSTGRES_HOST = "POSTGRES_HOST",
    POSTGRES_PORT = "POSTGRES_PORT",
    POSTGRES_USER = "POSTGRES_USER",
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD",
    POSTGRES_DB = "POSTGRES_DB",
}